__title__ = 'libkaede'
__description__ = 'Imageboard library for you <3'
__url__ = 'https://github.com/Hattshire/Kaede'
__version__ = '0.1.0a0'
__author__ = 'Oliver Hattshire'
__author_email__ = 'com.gmail:hattshire'
__license__ = 'GPLv3'
__copyright__ = 'Copyright 2018 Oliver Hattshire'
