language: python
sudo: required
python:
 - "3.6"
 - "3.7"
 - "3.8"
 - "3.9"
before_install:
 - "sudo apt-get -y install python3-gi-cairo python3-idna python3-urllib3 python3-certifi python3-chardet python3-appdirs python3-requests"
install:
 - "pip wheel ."
