language: python

python:
 - "3.6"
 - "3.7"
 - "3.8"
 - "3.9"

install:
 - "pip install flit"
 - "flit install --deps all"
 - "flit build"

script:
 - python -m "pytest"

after_success:
 - pip install coveralls
 - coverage run --source kaede -m pytest tests/
 - coveralls
