language: python
sudo: required
python:
 - "3.6"
 - "3.7"
 - "3.8"
install:
 - "pip install flit"
 - "flit install --deps all"
 - "flit build"
script:
 - python -m "pytest"
after_success:
 - coveralls
